#pragma once

//from glfw3.h

// Printable keys
#define CAP_KEY_SPACE              32
#define CAP_KEY_APOSTROPHE         39  
#define CAP_KEY_COMMA              44  
#define CAP_KEY_MINUS              45  
#define CAP_KEY_PERIOD             46  
#define CAP_KEY_SLASH              47  
#define CAP_KEY_0                  48
#define CAP_KEY_1                  49
#define CAP_KEY_2                  50
#define CAP_KEY_3                  51
#define CAP_KEY_4                  52
#define CAP_KEY_5                  53
#define CAP_KEY_6                  54
#define CAP_KEY_7                  55
#define CAP_KEY_8                  56
#define CAP_KEY_9                  57
#define CAP_KEY_SEMICOLON          59  
#define CAP_KEY_EQUAL              61  
#define CAP_KEY_A                  65
#define CAP_KEY_B                  66
#define CAP_KEY_C                  67
#define CAP_KEY_D                  68
#define CAP_KEY_E                  69
#define CAP_KEY_F                  70
#define CAP_KEY_G                  71
#define CAP_KEY_H                  72
#define CAP_KEY_I                  73
#define CAP_KEY_J                  74
#define CAP_KEY_K                  75
#define CAP_KEY_L                  76
#define CAP_KEY_M                  77
#define CAP_KEY_N                  78
#define CAP_KEY_O                  79
#define CAP_KEY_P                  80
#define CAP_KEY_Q                  81
#define CAP_KEY_R                  82
#define CAP_KEY_S                  83
#define CAP_KEY_T                  84
#define CAP_KEY_U                  85
#define CAP_KEY_V                  86
#define CAP_KEY_W                  87
#define CAP_KEY_X                  88
#define CAP_KEY_Y                  89
#define CAP_KEY_Z                  90
#define CAP_KEY_LEFT_BRACKET       91  
#define CAP_KEY_BACKSLASH          92  
#define CAP_KEY_RIGHT_BRACKET      93  
#define CAP_KEY_GRAVE_ACCENT       96  
#define CAP_KEY_WORLD_1            161 
#define CAP_KEY_WORLD_2            162 

// Function keys 
#define CAP_KEY_ESCAPE             256
#define CAP_KEY_ENTER              257
#define CAP_KEY_TAB                258
#define CAP_KEY_BACKSPACE          259
#define CAP_KEY_INSERT             260
#define CAP_KEY_DELETE             261
#define CAP_KEY_RIGHT              262
#define CAP_KEY_LEFT               263
#define CAP_KEY_DOWN               264
#define CAP_KEY_UP                 265
#define CAP_KEY_PAGE_UP            266
#define CAP_KEY_PAGE_DOWN          267
#define CAP_KEY_HOME               268
#define CAP_KEY_END                269
#define CAP_KEY_CAPS_LOCK          280
#define CAP_KEY_SCROLL_LOCK        281
#define CAP_KEY_NUM_LOCK           282
#define CAP_KEY_PRINT_SCREEN       283
#define CAP_KEY_PAUSE              284
#define CAP_KEY_F1                 290
#define CAP_KEY_F2                 291
#define CAP_KEY_F3                 292
#define CAP_KEY_F4                 293
#define CAP_KEY_F5                 294
#define CAP_KEY_F6                 295
#define CAP_KEY_F7                 296
#define CAP_KEY_F8                 297
#define CAP_KEY_F9                 298
#define CAP_KEY_F10                299
#define CAP_KEY_F11                300
#define CAP_KEY_F12                301
#define CAP_KEY_F13                302
#define CAP_KEY_F14                303
#define CAP_KEY_F15                304
#define CAP_KEY_F16                305
#define CAP_KEY_F17                306
#define CAP_KEY_F18                307
#define CAP_KEY_F19                308
#define CAP_KEY_F20                309
#define CAP_KEY_F21                310
#define CAP_KEY_F22                311
#define CAP_KEY_F23                312
#define CAP_KEY_F24                313
#define CAP_KEY_F25                314
#define CAP_KEY_KP_0               320
#define CAP_KEY_KP_1               321
#define CAP_KEY_KP_2               322
#define CAP_KEY_KP_3               323
#define CAP_KEY_KP_4               324
#define CAP_KEY_KP_5               325
#define CAP_KEY_KP_6               326
#define CAP_KEY_KP_7               327
#define CAP_KEY_KP_8               328
#define CAP_KEY_KP_9               329
#define CAP_KEY_KP_DECIMAL         330
#define CAP_KEY_KP_DIVIDE          331
#define CAP_KEY_KP_MULTIPLY        332
#define CAP_KEY_KP_SUBTRACT        333
#define CAP_KEY_KP_ADD             334
#define CAP_KEY_KP_ENTER           335
#define CAP_KEY_KP_EQUAL           336
#define CAP_KEY_LEFT_SHIFT         340
#define CAP_KEY_LEFT_CONTROL       341
#define CAP_KEY_LEFT_ALT           342
#define CAP_KEY_LEFT_SUPER         343
#define CAP_KEY_RIGHT_SHIFT        344
#define CAP_KEY_RIGHT_CONTROL      345
#define CAP_KEY_RIGHT_ALT          346
#define CAP_KEY_RIGHT_SUPER        347
#define CAP_KEY_MENU               348